Web/MyRecipes.Web/Controllers/HomeController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;

    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Data;
    using MyRecipes.Data.Common.Repositories;
    using MyRecipes.Data.Models;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels;
    using MyRecipes.Web.ViewModels.Home;

    public class HomeController : BaseController
    {
        private readonly IRecipesService recipesService;
        private readonly IGetCountsService countsService;
        private readonly ICategoriesService categoriesService;

        public HomeController(IGetCountsService countsService, IRecipesService recipesService, ICategoriesService categoriesService)
        {
            this.countsService = countsService;
            this.recipesService = recipesService;
            this.categoriesService = categoriesService;
        }

        public IActionResult Index()
        {
            var countsDto = this.countsService.GetCounts();

            // var viewModel = this.Mapper.Map<IndexViewModel>(countsDto); //shorter version
            var viewModel = new IndexViewModel
            {
                CategoriesCount = countsDto.CategoriesCount,
                ImagesCount = countsDto.ImagesCount,
                IngredientsCount = countsDto.IngredientsCount,
                RecipesCount = countsDto.RecipesCount,
                RandomRecipes = this.recipesService.GetRandom<IndexPageRecipeViewModel>(3),
                LatestRecipes = this.recipesService.GetLatest<IndexPageRecipeViewModel>(3),
                PopularCategories = this.categoriesService.GetPopular<IndexCategoryViewModel>(),
                TrendingRecipes = this.recipesService.GetTrending<IndexPageRecipeViewModel>(),
            };
            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/MyRecipes.Web/Controllers/RecipesController.cs
namespace MyRecipes.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
	using MyRecipes.Common;
	using MyRecipes.Data.Models;
    using MyRecipes.Services.Data;
	using MyRecipes.Web.ViewModels.Home;
	using MyRecipes.Web.ViewModels.Recipes;

    public class RecipesController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IRecipesService recipesService;
        private readonly UserManager<ApplicationUser> userManager;

        public RecipesController(
            ICategoriesService categoriesService,
            IRecipesService recipesService,
            UserManager<ApplicationUser> userManager)
        {
            this.categoriesService = categoriesService;
            this.recipesService = recipesService;
            this.userManager = userManager;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var inputModel = this.recipesService.GetById<EditRecipeInputModel>(id);
            inputModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
            return this.View(inputModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(int id, EditRecipeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            await this.recipesService.UpdateAsync(id, input);

            return this.RedirectToAction(nameof(this.ById), new { id }); // Redirect to ById View
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateRecipeInputModel();
            viewModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
            viewModel.LatestRecipes = this.recipesService.GetLatest<IndexPageRecipeViewModel>(5);
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateRecipeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                input.LatestRecipes = this.recipesService.GetLatest<IndexPageRecipeViewModel>(5);
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            try
            {
                // await this.recipesService.CreateAsync(input, user.Id, $"{this.env.Environment.ContentRootPath}/images");
                await this.recipesService.CreateAsync(input, user.Id, $"wwwroot/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            this.TempData["Message"] = "Recipe added successfully.";

            // TODO: Redirect to recipe info page
            return this.RedirectToAction("All");
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var viewModel = new RecipesListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                RecipesCount = this.recipesService.GetCount(),
                Recipes = this.recipesService.GetAll<RecipeInListViewModel>(id, ItemsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var recipe = this.recipesService.GetById<SingleRecipeViewModel>(id);
            return this.View(recipe);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            await this.recipesService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.All)); // Same like this.RedirectToAction("All")
        }
    }
}

Web/MyRecipes.Web/Controllers/SearchRecipesController.cs
namespace MyRecipes.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Recipes;
    using MyRecipes.Web.ViewModels.SearchRecipes;

    public class SearchRecipesController : BaseController
    {
        private readonly IRecipesService recipesService;
        private readonly IIngredientsService ingredientsService;

        public SearchRecipesController(IRecipesService recipesService, IIngredientsService ingredientsService)
        {
            this.recipesService = recipesService;
            this.ingredientsService = ingredientsService;
        }

        public IActionResult Index()
        {
            var viewModel = new SearchIndexViewModel
            {
                Ingredients = this.ingredientsService.GetAllPopular<IngredientNameIdViewModel>(),
            };
            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult List(SearchListInputModel input)
        {
            var viewModel = new ListViewModel()
            {
                Recipes = this.recipesService.GetByIngredients<RecipeInListViewModel>(input.Ingredients),
            };
            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult ListByCategory(int id)
        {
            var viewModel = new ListViewModel()
            {
                Recipes = this.recipesService.GetByCategoryId<RecipeInListViewModel>(id),
            };
            return this.View(viewModel);
        }
    }
}

Web/MyRecipes.Web/Views/Home/Index.cshtml
@using MyRecipes.Common
@model MyRecipes.Web.ViewModels.Home.IndexViewModel
@{
	this.ViewData["Title"] = "Home Page";
	int count = 1;
}

<!-- Random Recipe Start Here -->
<section class="padding-bottom-18">
	<div class="container">
		<div class="row">
			<div class="section-heading heading-dark">
				<h2 class="item-heading">POPULAR RECIPES</h2>
			</div>
			@foreach (var recipe in this.Model.RandomRecipes)
			{
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="product-box-layout1">
						<figure class="item-figure text-center">
							<a asp-controller="Recipes" asp-action="ById" asp-route-id="@recipe.Id">
								<img src="@recipe.ImageUrl" class="align-content-center"
									 alt="Product">
							</a>
						</figure>
						<div class="item-content">
							<span class="sub-title">@recipe.CategoryName</span>
							<h3 class="item-title">
								<a asp-controller="Recipes" asp-action="ById" asp-route-id="@recipe.Id">
									@recipe.Name
								</a>
							</h3>
							<ul class="item-rating">
								@for (int i = 1; i <= 5; i++)
								{
									<li class="star-@(i <= recipe.AverageVote ? "fill" : "empty")"><i class="fas fa-star"></i></li>
								}
								<li><span><span>@recipe.AverageVote.ToString("0.0") / 5</span></span> </li>
							</ul>
							<p>
								@(recipe.Instructions.Substring(0, 100) + "....")
							</p>
							<ul class="entry-meta">
								<li><a asp-controller="Recipes" asp-action="ById" asp-route-id="@recipe.Id"><i class="fas fa-clock"></i>@recipe.CookingTime.TotalMinutes Mins</a></li>
								<li><a asp-controller="Recipes" asp-action="ById" asp-route-id="@recipe.Id"><i class="fas fa-user"></i>by <span>@recipe.AddedByUserUserName</span></a></li>
							</ul>
						</div>
					</div>
				</div>
			}

		</div>
	</div>
</section>
<!-- Random Recipe End Here -->
<!-- Trending Recipe Start Here -->
<section class="padding-bottom-45">
	<div class="container">
		<div class="row gutters-60">
			<div class="col-lg-8">
				<div class="section-heading heading-dark">
					<h2 class="item-heading">TRENDING RECIPE</h2>
				</div>
				<div class="row">
					<div class="col-12">
						<div class="product-box-layout1">
							<figure class="item-figure text-center">
								<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[0].Id">
									<img src="@Model.TrendingRecipes[0].ImageUrl"
										 alt="Product">
								</a>
							</figure>
							<div class="item-content">
								<span class="sub-title">@Model.TrendingRecipes[0].CategoryName</span>
								<h2 class="item-title">
									<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[0].Id">
										@Model.TrendingRecipes[0].Name
									</a>
								</h2>
								<ul class="item-rating">
									@for (int i = 1; i <= 5; i++)
									{
										<li class="star-@(i <= Model.TrendingRecipes[0].AverageVote ? "fill" : "empty")"><i class="fas fa-star"></i></li>
									}
									<li><span><span>@Model.TrendingRecipes[0].AverageVote.ToString("0.0") / 5</span></span> </li>
								</ul>
								<p>
									@(Model.TrendingRecipes[0].Instructions.Substring(0, 200) + "....")
								</p>
								<ul class="entry-meta">
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[0].Id">
											<i class="fas fa-clock"></i>@Model.TrendingRecipes[0].CookingTime.TotalMinutes Mins
										</a>
									</li>
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[0].Id">
											<i class="fas fa-user"></i>by <span>@Model.TrendingRecipes[0].AddedByUserUserName</span>
										</a>
									</li>
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[0].Id">
											<i class="fas fa-heart"></i><span>11569</span> Likes
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-sm-6 col-12">
						<div class="product-box-layout1">
							<figure class="item-figure text-center">
								<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[1].Id">
									<img src="@Model.TrendingRecipes[1].ImageUrl"
										 alt="Product">
								</a>
							</figure>
							<div class="item-content">
								<span class="sub-title">@Model.TrendingRecipes[1].CategoryName</span>
								<h3 class="item-title">
									<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[1].Id">
										@Model.TrendingRecipes[1].Name
									</a>
								</h3>
								<ul class="item-rating">
									@for (int i = 1; i <= 5; i++)
									{
										<li class="star-@(i <= Model.TrendingRecipes[1].AverageVote ? "fill" : "empty")"><i class="fas fa-star"></i></li>
									}
									<li><span><span>@Model.TrendingRecipes[1].AverageVote.ToString("0.0") / 5</span></span> </li>
								</ul>
								<p>
									@(Model.TrendingRecipes[1].Instructions.Substring(0, 200) + "....")
								</p>
								<ul class="entry-meta">
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[1].Id">
											<i class="fas fa-clock"></i>@Model.TrendingRecipes[1].CookingTime.TotalMinutes Mins
										</a>
									</li>
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[1].Id">
											<i class="fas fa-user"></i>by <span>@Model.TrendingRecipes[1].AddedByUserUserName</span>
										</a>
									</li>
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[1].Id">
											<i class="fas fa-heart"></i><span>7681</span> Likes
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-sm-6 col-12">
						<div class="product-box-layout1">
							<figure class="item-figure text-center">
								<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[2].Id">
									<img src="@Model.TrendingRecipes[2].ImageUrl"
										 alt="Product">
								</a>
							</figure>
							<div class="item-content">
								<span class="sub-title">@Model.TrendingRecipes[2].CategoryName</span>
								<h3 class="item-title">
									<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[2].Id">
										@Model.TrendingRecipes[2].Name
									</a>
								</h3>
								<ul class="item-rating">
									@for (int i = 1; i <= 5; i++)
									{
										<li class="star-@(i <= Model.TrendingRecipes[2].AverageVote ? "fill" : "empty")"><i class="fas fa-star"></i></li>
									}
									<li><span><span>@Model.TrendingRecipes[2].AverageVote.ToString("0.0") / 5</span></span> </li>
								</ul>
								<p>
									@(Model.TrendingRecipes[2].Instructions.Substring(0, 200) + "....")
								</p>
								<ul class="entry-meta">
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[2].Id">
											<i class="fas fa-clock"></i>@Model.TrendingRecipes[2].CookingTime.TotalMinutes Mins
										</a>
									</li>
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[2].Id">
											<i class="fas fa-user"></i>by <span>@Model.TrendingRecipes[2].AddedByUserUserName</span>
										</a>
									</li>
									<li>
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@Model.TrendingRecipes[2].Id">
											<i class="fas fa-heart"></i><span>9371</span> Likes
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12">
					<img src="~/images/src/michaelstrahan1.jpg">
				</div>
			</div>
			<div class="col-lg-4 sidebar-widget-area sidebar-break-md">

				<div class="widget">
					<div class="section-heading heading-dark">
						<h3 class="item-heading">CHECK FOR MORE</h3>
					</div>
					<div class="widget-follow-us">
						<ul>
							<li class="single-item">
								<a href="https://www.facebook.com/groups/bgkulinar/?locale=bg_BG" target="_blank">
									<i class="fab fa-facebook-f"></i>LIKE ME ON
								</a>
							</li>
							<li class="single-item">
								<a href="https://twitter.com/RecipesIdeas" target="_blank">
									<i class="fab fa-twitter"></i>LIKE ME
								</a>
							</li>
							<li class="single-item">
								<a href="https://www.instagram.com/_matekitchen_/" target="_blank">
									<i class="fab fa-instagram"></i>LIKE ME
								</a>
							</li>
							<li class="single-item">
								<a href="@Html.Raw("https://youtube.com/@zvezdevBG")" target="_blank">
									<i class="fab fa-youtube"></i>Subscribe
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="widget">
					<div class="section-heading heading-dark">
						<h3 class="item-heading">LATEST RECIPES</h3>
					</div>
					<div class="widget-latest">
						<ul class="block-list">
							@foreach (var recipe in Model.LatestRecipes)
							{
								<li class="single-item">
									<div class="item-img">
										<a asp-controller="Recipes" asp-action="ById" asp-route-id="@recipe.Id"><img src="@recipe.ImageUrl" width="90" height="90" alt="Post"></a>
										<div class="count-number">@(count++)</div>
									</div>
									<div class="item-content">
										<div class="item-ctg">@recipe.CategoryName</div>
										<h4 class="item-title">
											<a asp-controller="Recipes" asp-action="ById" asp-route-id="@recipe.Id">
												@recipe.Name
											</a>
										</h4>
										<div class="item-post-by">
											<a asp-controller="Recipes" asp-action="ById" asp-route-id="@recipe.Id">
												<i class="fas fa-user"></i><span>by</span>
												@recipe.AddedByUserUserName
											</a>
										</div>
									</div>
								</li>
							}
						</ul>
					</div>
				</div>
				<div class="widget">
					<div class="section-heading heading-dark">
						<h3 class="item-heading">POPULAR CATEGORIES</h3>
					</div>
					<div class="widget-categories">
						<ul>
							@foreach (var category in Model.PopularCategories)
							{
								<li>
									<a asp-controller="SearchRecipes" asp-action="ListByCategory" asp-route-id="@category.Id">
										@category.Name
										<span>@category.Recipes.Count</span>
									</a>
								</li>
							}
						</ul>
					</div>
				</div>
				<div class="widget">
					<div class="section-heading heading-dark">
						<h3 class="item-heading">We have:</h3>
					</div>
					<div class="widget-tag">
						<ul>
							<li class="">
								<a href="#"> Recipes: @Model.RecipesCount </a>
							</li>
							<li>
								<a href="#">Categories: @Model.CategoriesCount </a>
							</li>
							<li>
								<a href="#">Images: @Model.ImagesCount </a>
							</li>
							<li>
								<a href="#">Ingredients: @Model.IngredientsCount </a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Trending Recipe End Here -->